name: show_room
publish_to: 'none'

description: Demo scene overlay app

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  tflite_flutter: ^0.10.4
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/yolo11n.tflite
    - assets/models/yolo11n-seg.tflite
    - assets/models/labels.txt
